# Generated by Django 5.0.2 on 2025-05-09 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('cycle', models.CharField(choices=[('R', 'Regular'), ('I', 'Irregular')], max_length=1)),
                ('cycle_length', models.FloatField()),
                ('lh_fsh_ratio', models.FloatField()),
                ('weight_gain', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('hair_growth', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('follicle_no_l', models.FloatField()),
                ('follicle_no_r', models.FloatField()),
                ('hip', models.FloatField()),
                ('skin_darkening', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('lifestyle_score', models.FloatField()),
                ('prediction', models.IntegerField(choices=[(0, 'Low Risk'), (1, 'High Risk')])),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
